name: Build Real Tor APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npx cap add android
      - run: npx cap copy android
      - run: |
          echo "maven { url \"https://jitpack.io\" }" >> android/build.gradle
      - run: chmod +x android/gradlew && cd android &&./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: TorChat-REAL-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk